spring:
  application:
    name: yonghe-min-feign
  rabbitmq:
        host: 10.20.0.66
        port: 5672
        username: shuma
        password: q1w2e3r4
  sleuth:
        web:
          client:
            enabled: true
        sampler:
          probability: 1.0 # 将采样比例设置为 1.0，也就是全部都需要。默认是 0.1
  zipkin:
        base-url: http://localhost:9411/ # 指定了 Zipkin 服务器的地址
eureka:
  client:
    service-url:
      client:
          registerWithEureka: false
          fetchRegistry: false
          defaultZone: http://localhost:8761/yonghe/
server:
  port: 9000
feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream